# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1189, 712)
        Main.setWindowOpacity(1.0)
        self.verticalLayoutWidget = QtWidgets.QWidget(Main)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1161, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutWidget = QtWidgets.QWidget(Main)
        self.layoutWidget.setGeometry(QtCore.QRect(940, 560, 186, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Compute_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Compute_button.setFont(font)
        self.Compute_button.setObjectName("Compute_button")
        self.verticalLayout_2.addWidget(self.Compute_button)
        self.Compute_button_reset = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Compute_button_reset.setFont(font)
        self.Compute_button_reset.setObjectName("Compute_button_reset")
        self.verticalLayout_2.addWidget(self.Compute_button_reset)
        self.Compute_button_feedback = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Compute_button_feedback.setFont(font)
        self.Compute_button_feedback.setObjectName("Compute_button_feedback")
        self.verticalLayout_2.addWidget(self.Compute_button_feedback)
        self.layoutWidget1 = QtWidgets.QWidget(Main)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 540, 911, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stock_code = QtWidgets.QLabel(self.layoutWidget1)
        self.stock_code.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.stock_code.setFont(font)
        self.stock_code.setTextFormat(QtCore.Qt.AutoText)
        self.stock_code.setAlignment(QtCore.Qt.AlignCenter)
        self.stock_code.setObjectName("stock_code")
        self.gridLayout.addWidget(self.stock_code, 0, 0, 1, 1)
        self.stock_code_text = QtWidgets.QTextEdit(self.layoutWidget1)
        self.stock_code_text.setMaximumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.stock_code_text.setFont(font)
        self.stock_code_text.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.stock_code_text.setObjectName("stock_code_text")
        self.gridLayout.addWidget(self.stock_code_text, 0, 1, 1, 2)
        self.window_size_label = QtWidgets.QLabel(self.layoutWidget1)
        self.window_size_label.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.window_size_label.setFont(font)
        self.window_size_label.setTextFormat(QtCore.Qt.AutoText)
        self.window_size_label.setAlignment(QtCore.Qt.AlignCenter)
        self.window_size_label.setObjectName("window_size_label")
        self.gridLayout.addWidget(self.window_size_label, 0, 3, 1, 1)
        self.window_size_text = QtWidgets.QTextEdit(self.layoutWidget1)
        self.window_size_text.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.window_size_text.setFont(font)
        self.window_size_text.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.window_size_text.setObjectName("window_size_text")
        self.gridLayout.addWidget(self.window_size_text, 0, 4, 1, 1)
        self.sample_frequency_label = QtWidgets.QLabel(self.layoutWidget1)
        self.sample_frequency_label.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.sample_frequency_label.setFont(font)
        self.sample_frequency_label.setTextFormat(QtCore.Qt.AutoText)
        self.sample_frequency_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sample_frequency_label.setObjectName("sample_frequency_label")
        self.gridLayout.addWidget(self.sample_frequency_label, 1, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 2, 1, 1)
        self.iiteration_times_label = QtWidgets.QLabel(self.layoutWidget1)
        self.iiteration_times_label.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.iiteration_times_label.setFont(font)
        self.iiteration_times_label.setTextFormat(QtCore.Qt.AutoText)
        self.iiteration_times_label.setAlignment(QtCore.Qt.AlignCenter)
        self.iiteration_times_label.setObjectName("iiteration_times_label")
        self.gridLayout.addWidget(self.iiteration_times_label, 1, 3, 1, 1)
        self.iteration_times_text = QtWidgets.QTextEdit(self.layoutWidget1)
        self.iteration_times_text.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.iteration_times_text.setFont(font)
        self.iteration_times_text.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.iteration_times_text.setObjectName("iteration_times_text")
        self.gridLayout.addWidget(self.iteration_times_text, 1, 4, 1, 1)
        self.trade_button = QtWidgets.QPushButton(Main)
        self.trade_button.setGeometry(QtCore.QRect(960, 740, 184, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.trade_button.setFont(font)
        self.trade_button.setObjectName("trade_button")

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "stocks"))
        self.Compute_button.setText(_translate("Main", "Compute"))
        self.Compute_button_reset.setText(_translate("Main", "Reset"))
        self.Compute_button_feedback.setText(_translate("Main", "Feedback"))
        self.stock_code.setText(_translate("Main", "Stock Code"))
        self.stock_code_text.setPlaceholderText(_translate("Main", "AMZN"))
        self.window_size_label.setText(_translate("Main", "Window Size"))
        self.window_size_text.setPlaceholderText(_translate("Main", "3"))
        self.sample_frequency_label.setText(_translate("Main", "Sample Frequency"))
        self.comboBox.setCurrentText(_translate("Main", " 1 min"))
        self.comboBox.setItemText(0, _translate("Main", " 1 min"))
        self.comboBox.setItemText(1, _translate("Main", "15 min"))
        self.comboBox.setItemText(2, _translate("Main", "30 min"))
        self.comboBox.setItemText(3, _translate("Main", "60 min"))
        self.iiteration_times_label.setText(_translate("Main", "Iteration Times"))
        self.iteration_times_text.setPlaceholderText(_translate("Main", "50"))
        self.trade_button.setText(_translate("Main", "Trade"))
